lib/earthquake_tracker_web/router.ex
defmodule EarthquakeTrackerWeb.Router do
  use EarthquakeTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EarthquakeTrackerWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EarthquakeTrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/tracked_earthquakes", TrackedEarthquakeController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
    resources "/query_earthquake", EarthquakeQueryController, only: [:show], singleton: true
    get "/query_earthquake", EarthquakeQueryController, :query_earthquake
    post "/query_earthquake", EarthquakeQueryController, :query_earthquake
    get "/query_earthquake/send_email", EarthquakeQueryController, :send_email
    resources "/news", NewsQueryController, only: [:index]
  end

  # Other scopes may use custom stacks.
  # scope "/api", EarthquakeTrackerWeb do
  #   pipe_through :api
  # end
end

lib/earthquake_tracker_web/views/layout_view.ex
defmodule EarthquakeTrackerWeb.LayoutView do
  use EarthquakeTrackerWeb, :view
end

lib/earthquake_tracker_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, shrink-to-fit=no, user-scalable=no"/>
    <title>Earthquake Tracker</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-sm navbar-light bg-white">
        <a class="navbar-brand" href="/">Earthquake Tracker</a>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <%= link("News", to: Routes.news_query_path(@conn, :index), class: "nav-link") %>
          </li>
          <%= if @current_user do %>
            <li class="nav-item">
              <%= link("Tracked", to: Routes.tracked_earthquake_path(@conn, :index, %{"id" => @current_user.id}), class: "nav-link") %>
            </li>

            <%= if @current_user.admin do %>
              <li class="nav-item">
                <a class="nav-link" href="/users">Users</a>
              </li>
            <% end %>
          <% end %>
        </ul>
        <%= if @current_user do %>
          <div class="ml-auto">
            <p class="user-info">
              <%= link(@current_user.email, to: Routes.user_path(@conn, :show, @current_user)) %> |
              <%= link("Logout", to: Routes.session_path(@conn, :delete), method: :delete) %>
            </p>
          </div>
        <% else %>
          <div class="ml-auto">
            <%= form_for @conn, Routes.session_path(@conn, :create), [class: "form-inline"], fn f -> %>
              <%= text_input f, :email, class: "form-control col-4", placeholder: "email", id: "email-input" %>
              <%= password_input f, :password, class: "form-control col-4", placeholder: "password", id: "password-input" %>
              <%= submit "Login", class: "btn btn-link" %> |
              <%= link "Register", to: Routes.user_path(@conn, :new), class: "btn btn-link" %>
            <% end %>
          </div>
        <% end %>
      </nav>

      <div class="row">
        <div class="col-12">
          <%= if get_flash(@conn, :info) do %>
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <% end %>
          <%= if get_flash(@conn, :error) do %>
            <p class="alert alert-danger" role="alert">
              <%= get_flash(@conn, :error) %>
            </p>
          <% end %>
        </div>
      </div>

      <%= render @view_module, @view_template, assigns %>
    </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAWWCNo1QwAQKGBL4ZnbGbS3NITuryM-9U"></script>
  </body>
</html>

lib/earthquake_tracker_web/templates/layout/email.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, shrink-to-fit=no, user-scalable=no"/>
    <title>Earthquake Tracker</title>
  </head>
  <body>
    <h2>Tracked Area: <%= @name %></h2>
    <p>Number of earthquakes: <%= @num_eq %></p>

    <table class="table table-striped">
      <thead class="thead-light">
        <tr>
          <th>Place</th>
          <th>Time</th>
          <th>Magnitude</th>
          <th>MMI</th>
          <th>Longitude</th>
          <th>Latitude</th>
          <th>Depth</th>
        </tr>
      </thead>
      <tbody>
      <%= for eq <- @eq_data do %>
        <tr>
          <td><%= eq.place %></td>
          <td><%= case DateTime.from_unix(eq.time, :millisecond) do {:ok, time} -> time end %></td>
          <td><%= eq.mag %></td>
          <td><%= eq.mmi %></td>
          <td><%= eq.longitude %></td>
          <td><%= eq.latitude %></td>
          <td><%= eq.depth %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </body>
</html>