lib/earthquake_tracker_web/router.ex
defmodule EarthquakeTrackerWeb.Router do
  use EarthquakeTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EarthquakeTrackerWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EarthquakeTrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/tracked_earthquakes", TrackedEarthquakeController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
    resources "/query_earthquake", EarthquakeQueryController, only: [:show], singleton: true
    get "/query_earthquake", EarthquakeQueryController, :query_earthquake
    post "/query_earthquake", EarthquakeQueryController, :query_earthquake
    get "/query_earthquake/send_email", EarthquakeQueryController, :send_email
    resources "/news", NewsQueryController, only: [:index]
  end

  # Other scopes may use custom stacks.
  # scope "/api", EarthquakeTrackerWeb do
  #   pipe_through :api
  # end
end

lib/earthquake_tracker_web/controllers/earthquake_query_controller.ex
defmodule EarthquakeTrackerWeb.EarthquakeQueryController do
  use EarthquakeTrackerWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def show(conn, %{"eq_data" => eq_data, "num_eq" => num_eq, "start_time" => start_time, "end_time" => end_time}) do
    render(conn, "show.html", eq_data: eq_data, num_eq: num_eq, start_time: start_time, end_time: end_time)
  end

  def query_earthquake(conn, %{"start_time" => start_time,
      "end_time" => end_time, "location" => location, "sq_min_lat" => sq_min_lat,
      "sq_max_lat" => sq_max_lat, "sq_min_lng" => sq_min_lng, "sq_max_lng" => sq_max_lng,
      "ci_lat" => ci_lat, "ci_lng" => ci_lng, "ci_max_rad" => ci_max_rad, "min_mag" => min_mag,
      "max_mag" => max_mag}) do

    data = query_eq_data(start_time,  end_time, location, sq_min_lat, sq_max_lat, sq_min_lng,
      sq_max_lng, ci_lat, ci_lng, ci_max_rad, min_mag, max_mag)

    earthquake_data = Map.get(data, :earthquake_data)
    num_of_earthquakes = Map.get(data, :num_of_earthquakes)

    if num_of_earthquakes != -1 do
      conn
      |> render("show.html", eq_data: earthquake_data, num_eq: num_of_earthquakes,
           start_time: start_time, end_time: end_time)
    else
      conn
      |> redirect(to: Routes.page_path(conn, :index))
    end
  end

  def query_eq_data(start_time, end_time, location, sq_min_lat, sq_max_lat, sq_min_lng, sq_max_lng,
         ci_lat, ci_lng, ci_max_rad, min_mag, max_mag) do
    url = base_string() <> add_time(start_time, end_time)
    url =
      if location == "square" do
        url <> add_square(sq_min_lat, sq_max_lat, sq_min_lng, sq_max_lng)
      else
        if location == "circle" do
          url <> add_circle(ci_lat, ci_lng, ci_max_rad)
        else
          url
        end
      end
    url =
      if min_mag != "" || max_mag != "" do
        url <> add_magnitude(min_mag, max_mag)
      else
        url
      end

    headers = []
    params = []

    parsed =
      case HTTPoison.get(url, headers, params: params) do
        {:ok, response} -> parse_eq_data(response)
        {:error, reason} -> IO.puts reason
      end

    if parsed do
      %{:metadata => metadata, :features => features} = parsed
      num_of_earthquakes = Map.get(metadata, "count")
      earthquake_data = Enum.map features, fn eq ->
        [long | [lat | [depth]]] = Map.get(Map.get(eq, "geometry"), "coordinates")
        props = Map.get(eq, "properties")
        %{mag: Map.get(props, "mag"), place: Map.get(props, "place"), time: Map.get(props, "time"),
          mmi: Map.get(props, "mmi"), longitude: long, latitude: lat, depth: depth}
      end
      %{earthquake_data: earthquake_data, num_of_earthquakes: num_of_earthquakes}
    else
      %{earthquake_data: [], num_of_earthquakes: -1}
    end
  end

  defp parse_eq_data(data) do
    decoded_data = Poison.decode(data.body)
    data_part = elem(decoded_data, 1)
    metadata = Map.get(data_part, "metadata")
    features = Map.get(data_part, "features")
    %{metadata: metadata, features: features}
  end

  defp base_string(), do: "https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson"

  defp add_time(start_time, end_time) do
    "&starttime=" <> start_time <> "&endtime=" <> end_time
  end

  defp add_square(min_lat, max_lat, min_lng, max_lng) do
    "&minlatitude=" <> min_lat <> "&maxlatitude=" <> max_lat
    <> "&minlongitude=" <> min_lng <> "&maxlongitude=" <> max_lng
  end

  defp add_circle(lat, lng, rad) do
    "&latitude=" <> lat <> "&longitude=" <> lng <> "&maxradius=" <> rad
  end

  defp add_magnitude(min_mag, max_mag) do
    "&minmagnitude=" <> min_mag <> "&maxmagnitude=" <> max_mag
  end
end

lib/earthquake_tracker_web/templates/earthquake_query/index.html.eex
<div class="row">
  <div class="col-12">
    <%= form_for @conn, Routes.earthquake_query_path(@conn, :query_earthquake), fn f -> %>
      <div class="row">
        <div class="form-group col-6">
          <%= label f, :start_time, class: "control-label" %>
          <%= date_input f, :start_time, class: "form-control", required: true %>
          <%= error_tag f, :start_time %>
        </div>
        <div class="form-group col-6">
          <%= label f, :end_time, class: "control-label" %>
          <%= date_input f, :end_time, class: "form-control", required: true %>
          <%= error_tag f, :end_time %>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-12">
          <%= label f, :location, class: "control-label" %>
          <%= select f, :location, ["Square": "square", "Circle": "circle"],
              prompt: "Any Location", class: "form-control", id: "size-select" %>
          <%= error_tag f, :location %>
        </div>
      </div>
      <div class="row" style="display: none" id="square-selected">
        <div class="form-group col-6">
          <%= label f, "Minimum Latitude (default -90)", class: "control-label" %>
          <%= number_input f, :sq_min_lat, class: "form-control", value: -90, min: -90, max: 90 %>
          <%= error_tag f, :sq_min_lat %>

          <%= label f, "Maximum Latitude (default 90)", class: "control-label" %>
          <%= number_input f, :sq_max_lat, class: "form-control", value: 90, min: -90, max: 90 %>
          <%= error_tag f, :sq_max_lat %>
        </div>
        <div class="form-group col-6">
          <%= label f, "Minimum Longitude (default -180)", class: "control-label" %>
          <%= number_input f, :sq_min_lng, class: "form-control", value: -180, min: -180, max: 180 %>
          <%= error_tag f, :sq_min_lng %>

          <%= label f, "Maximum Longitude (default 180)", class: "control-label" %>
          <%= number_input f, :sq_max_lng, class: "form-control", value: 180, min: -180, max: 180 %>
          <%= error_tag f, :sq_max_lng %>
        </div>
      </div>
      <div class="row" style="display: none" id="circle-selected">
        <div class="form-group col-12">
          <div class="row">
            <div class="col-6">
              <%= label f, "Latitude", class: "control-label" %>
              <%= number_input f, :ci_lat, class: "form-control", value: 0, min: -90, max: 90 %>
              <%= error_tag f, :ci_lat %>
            </div>
            <div class="col-6">
              <%= label f, "Longitude", class: "control-label" %>
              <%= number_input f, :ci_lng, class: "form-control", value: 0, min: -180, max: 180 %>
              <%= error_tag f, :ci_lng %>
            </div>
          </div>
        </div>
        <div class="form-group col-12">
          <%= label f, "Max Radius (default 180)", class: "control-label" %>
          <%= number_input f, :ci_max_rad, class: "form-control", value: 180, min: 0, max: 180 %>
          <%= error_tag f, :ci_max_rad %>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-12">
          <div class="row">
            <div class="col-6">
              <%= label f, "Minimum Magnitude", class: "control-label" %>
              <%= number_input f, :min_mag, step: "any", class: "form-control" %>
              <%= error_tag f, :min_mag %>
            </div>
            <div class="col-6">
              <%= label f, "Maximum Magnitude", class: "control-label" %>
              <%= number_input f, :max_mag, step: "any", class: "form-control" %>
              <%= error_tag f, :max_mag %>
            </div>
          </div>
        </div>
      </div>
      <%= submit "Query", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

lib/earthquake_tracker_web/templates/earthquake_query/show.html.eex
<div class="row">
  <div class="col-12">
    <div id="map"></div>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <h1>All Earthquakes from <%= @start_time %> to <%= @end_time %></h1>

    <h3>Number of Earthquakes Queried: <%= @num_eq %></h3>

    <table class="table table-striped">
      <thead class="thead-light">
        <tr>
          <th>Place</th>
          <th>Time</th>
          <th>Magnitude</th>
          <th>MMI</th>
          <th>Longitude</th>
          <th>Latitude</th>
          <th>Depth</th>
        </tr>
      </thead>
      <tbody>
    <%= for eq <- @eq_data do %>
        <tr>
          <td><%= eq.place %></td>
          <td><%= case DateTime.from_unix(eq.time, :millisecond) do {:ok, time} -> time end %></td>
          <td><%= eq.mag %></td>
          <td><%= eq.mmi %></td>
          <td><%= eq.longitude %></td>
          <td><%= eq.latitude %></td>
          <td><%= eq.depth %></td>
        </tr>
    <% end %>
      </tbody>
    </table>
  </div>
</div>
<script>
  // pass in the earthquake data to app.js
  window.eq_data = <%= raw Jason.encode!(@eq_data) %>;
  console.log(window.eq_data);
</script>